vevent location backcompat
microformats/php-mf2 pull request #241
Opened 2022-07-08 04:01 UTC by gRegorLove

Originally this was PR #201 which got stale. I believe PR #234 fixed issue #184 properly. This just adds back the original tests that 201 was going to add, and a small update in Parser.php to indicate the `location` and `vcard` classes were updated during backcompat.

These tests passed as soon as I added them, so I think #184 is resolved.

2022-09-25 20:37 UTC, gRegorLove commented
Once #243 is merged, these builds should work again.

2024-03-08 06:13 UTC, artlung approved these changes

2024-03-08 20:35 UTC, tantek requested changes
Much better! Fixed the prior mentioned issues, however in looking at it more closely I found this likely unintended dates inconsistency:

There are two instances of:
`<time class="dtstart" datetime="2012-10-10">10 Nov 2012</time>`

Problem: October in the ISO8601 datetime attribute vs "Nov" in the visible text content. Not sure which it should be but it should be consistent (unless this is testing an inconsistency error?).

2024-03-08 21:14 UTC, tantek approved these changes

2024-03-08 21:59 UTC, merged